@url = http://localhost:3000

###
POST {{url}}/users
Content-Type: application/json

{
  "login": "testuser",
  "tabel": "TAB123",
  "password": "password123"
}

###
POST {{url}}/auth/login
Content-Type: application/json

{
  "login": "testuser",
  "tabel": "TAB123",
  "password": "password123"
}

### GET test user

{{url}}/users/testuser

